language: generic

matrix:
  include:
    # Linux and GCC
    - os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
      env:
        - CC_COMPILER=gcc-6
        - CXX_COMPILER=g++-6
    # llvm-toolchain-trusty does not look whitelisted, yet:
    #    https://github.com/travis-ci/apt-source-whitelist
    # - os: linux
    #   dist: trusty
    #   sudo: required
    #   addons:
    #     apt:
    #       sources:
    #         - llvm-toolchain-trusty
    #       packages:
    #         - clang-3.8
    #   env: 
    #     - CC_COMPILER=clang-3.8
    #     - CXX_COMPILER=clang++-3.8
    # OS X and Clang
    - os: osx
      osx_image: xcode7.3
      env:
        - CC_COMPILER=cc
        - CXX_COMPILER=c++
    # OS X and GCC
    - os: osx
      osx_image: xcode7.3
      env:
        - CC_COMPILER=gcc-6
        - CXX_COMPILER=g++-6
        - TEST_NAME="OSX_GCC"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libhdf5-dev hdf5-tools libpython-dev python-h5py python-numpy ninja-build ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CMAKE_EXEC=cmake ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CTEST_EXEC=ctest ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo curl -L -O https://cmake.org/files/v3.6/cmake-3.6.0-Linux-x86_64.tar.gz ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo tar xf cmake-3.6.0-Linux-x86_64.tar.gz ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CMAKE_EXEC=`pwd`/cmake-3.6.0-Linux-x86_64/bin/cmake ; fi
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CTEST_EXEC=`pwd`/cmake-3.6.0-Linux-x86_64/bin/ctest ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then CMAKE_EXEC=cmake ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then CTEST_EXEC=ctest ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update > /dev/null ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated cmake || brew upgrade cmake ; fi
  - if [[ "$TEST_NAME" == "OSX_GCC" ]]; then brew reinstall gcc ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install md5sha1sum ninja python homebrew/python/numpy homebrew/science/hdf5 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip install h5py ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then PY_INC=`python-config --includes | grep -o '\-I[^ ]*' | head -n 1 | cut -c 3-` ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then PY_LIB=`python-config --ldflags | grep -o '\-L[^ ]*' | head -n 1 | cut -c 3- | xargs -I % find % -name libpython*.dylib` ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then EXTRA_FLAGS="-DPYTHON_LIBRARY=${PY_LIB} -DPYTHON_INCLUDE_DIR=${PY_INC}" ; fi
  - ./get_dependencies.sh

script:
  - mkdir build
  - cd build
  - CC=$CC_COMPILER CXX=$CXX_COMPILER $CMAKE_EXEC -DSTRICT_BUILD=ON -DUSE_HDF5=ON -DUSE_PYTHON=ON ${EXTRA_FLAGS} .. -GNinja
  - ninja -v -j 2
  - $CTEST_EXEC -j 2 --output-on-failure
